name: tests
on: push
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make smoke
  clang-tidy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make lint
